/**
 * Client-side PDF generation for briefings.
 *
 * Renders a styled HTML representation of a briefing to PDF via html2pdf.js
 * (which uses html2canvas + jsPDF under the hood). The PDF matches the
 * warm visual style of the PWA — not a plain text dump.
 *
 * Upstream: `app/src/components/AppHeader/AppHeader.tsx` — download button
 * Downstream: html2pdf.js — rendering engine
 * See also: `app/src/domain/briefing/types.ts::Briefing` — input type
 * Do NOT: Call on the server — this is a browser-only function (requires DOM)
 */

import type { Briefing } from '@/domain/briefing';
import { API_BASE, headers } from '@/lib/api';

/**
 * Generates a PDF from a briefing and triggers a browser download.
 *
 * Renders the briefing sections into a temporary hidden DOM element,
 * converts to PDF, triggers download, then fires a background POST
 * to /exports to record the event and upload the artifact.
 *
 * @param briefing - The full Briefing object with sections and metadata
 * @returns Promise that resolves when the download is triggered
 */
export async function generateAndDownloadPdf(briefing: Briefing): Promise<void> {
  // Dynamic import — html2pdf.js is large, only load when needed
  const html2pdf = (await import('html2pdf.js')).default;

  // Build styled HTML for the PDF
  const container = document.createElement('div');
  container.style.cssText = 'width: 700px; padding: 40px; font-family: Georgia, serif; color: #2d2824; background: #fff;';

  const typeLabel = briefing.type === 'work' ? 'Work' : briefing.type === 'news' ? 'News' : briefing.type;
  const dateString = new Date(briefing.generatedAt).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });

  const severityColors: Record<string, string> = {
    flag: '#c0392b',
    warn: '#d4956a',
    info: '#8a8078',
  };

  let sectionsHtml = '';
  for (const section of briefing.sections) {
    const borderColor = severityColors[section.severity] ?? severityColors.info;
    const severityLabel = section.severity === 'flag' ? '🔴 FLAG' : section.severity === 'warn' ? '🟡 WARNING' : '';

    sectionsHtml += `
      <div style="border-left: 4px solid ${borderColor}; padding: 16px 20px; margin-bottom: 20px; background: #fafaf8; border-radius: 4px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
          <h3 style="margin: 0; font-size: 16px; font-style: italic; color: #2d2824;">${section.label}</h3>
          ${severityLabel ? `<span style="font-size: 11px; font-weight: 600;">${severityLabel}</span>` : ''}
        </div>
        <div style="font-size: 13px; line-height: 1.6; color: #3a342c; white-space: pre-wrap;">${escapeHtml(section.content)}</div>
      </div>
    `;
  }

  container.innerHTML = `
    <div style="border-bottom: 2px solid #c87941; padding-bottom: 16px; margin-bottom: 24px;">
      <h1 style="margin: 0 0 4px 0; font-size: 28px; font-style: italic; color: #c87941;">Chief of Staff</h1>
      <h2 style="margin: 0 0 8px 0; font-size: 20px; color: #2d2824;">${typeLabel} Briefing</h2>
      <p style="margin: 0; font-size: 12px; color: #8a8078; font-family: monospace;">
        ${dateString} · #${briefing.metadata.briefingNumber ?? '—'}
      </p>
    </div>
    ${sectionsHtml}
    <div style="border-top: 1px solid #e0ddd8; padding-top: 12px; margin-top: 24px; text-align: center;">
      <p style="font-size: 10px; color: #8a8078; font-family: monospace;">
        Generated by Chief of Staff · ${new Date().toISOString().slice(0, 10)}
      </p>
    </div>
  `;

  // Generate filename
  const dateSlug = briefing.generatedAt.slice(0, 10);
  const filename = `briefing-${typeLabel.toLowerCase()}-${dateSlug}.pdf`;

  // Render to PDF and trigger download
  const pdfBlob: Blob = await html2pdf()
    .set({
      margin: [10, 10, 10, 10],
      filename,
      image: { type: 'jpeg', quality: 0.95 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    })
    .from(container)
    .outputPdf('blob');

  // Trigger browser download
  const downloadUrl = URL.createObjectURL(pdfBlob);
  const downloadLink = document.createElement('a');
  downloadLink.href = downloadUrl;
  downloadLink.download = filename;
  document.body.appendChild(downloadLink);
  downloadLink.click();
  document.body.removeChild(downloadLink);
  URL.revokeObjectURL(downloadUrl);

  // Fire-and-forget: record export + upload to R2
  try {
    const formData = new FormData();
    formData.append('briefingId', briefing.id);
    formData.append('exportType', 'pdf');
    formData.append('file', pdfBlob, filename);

    await fetch(`${API_BASE}/exports`, {
      method: 'POST',
      headers: { Authorization: headers().Authorization ?? '' },
      body: formData,
    });
  } catch {
    // Non-fatal — PDF is already downloaded locally
  }
}

/** Escapes HTML special characters to prevent injection in the PDF template. */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
